### ISSUE TITLE
Dependency `medflex` archived for issues

### ISSUE THREAD

**Issue by csducate** [BS1125/CMAverse#36]
I tried to install `CMAverse` on my new work computer and discovered that the dependency `medflex` is no longer available on CRAN. Apparently it was pulled from the repository and archived on 2023-04-13 because it failed multiple checks, and its errors were not updated in a timely manner (see [here](https://cran.r-project.org/web/packages/medflex/index.html)).

Unfortunately, this makes `CMAverse` uninstallable. I considered downloading and installing an archived version of `medflex`, but given that I don't understand the nature of the error, I worry it would cause issues downstream (even if it seemed like it was working).

**Comment by ChadFibke** [comment]
Hi @csducate,

What modeling approach do you intend on running (example: rb, wb, iorw, ne, msm, gformula) for your analysis? I ask because the `medflex` dependency is installed and only  imports `neImpute()` [here](https://github.com/BS1125/CMAverse/blob/6a7f68ad0895f76bdb366a8d7774125572e0b469/R/cmest.R#L408) , which is only used if you specify `cmest( model = "ne" ... )` [here](https://github.com/BS1125/CMAverse/blob/6a7f68ad0895f76bdb366a8d7774125572e0b469/R/est.ne.R#L26) . I believe you could  install an archived version of medflex for `CMAverse` installation purposes, and carry on with your analysis if you are not using a natural effects model!

Best,
Chad

**Comment by BS1125** [comment]
Hi all, medflex has been removed from our dependencies. Thank you for informing us!
